version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
        - ${WEBAPP_STRORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
        - "6379:6379"
  
  orderdb:
    container_name: orderdb
    ports:
        - "1433:1433"
    environment: 
        SA_PASSWORD: "Strongman@1234"
        ACCEPT_EULA: "Y"
    
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "15672:15672"
        
  catalog.api:
    container_name: catalogapi    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "EventBus:Hostname=rabbitmq"
    depends_on:
        - catalogdb
        - rabbitmq
    volumes:
        - ${HOME}/.microsoft/usersecretes/:/root/.microsoft/usersecretes
        - ${HOME}/.aspnet/https/:/root/.aspnet/https/
    ports:
      - "8000:80"


  basket.api:
    container_name: basketapi    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:Hostname=rabbitmq"
    depends_on:
        - basketdb
        - rabbitmq
    volumes:
        - ${HOME}/.microsoft/usersecretes/:/root/.microsoft/usersecretes
        - ${HOME}/.aspnet/https/:/root/.aspnet/https/
    ports:
      - "8001:80"

  ordering.api:
    container_name: orderingapi
    restart: on-failure
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "ConnectionStrings:OrderConnection=Server=LAPTOP-59CMI8H3;Database=master;User Id=sa;Password=Strongman@1234"
        - "EventBus:Hostname=rabbitmq"
    depends_on:
        - orderdb
        - rabbitmq
    volumes:
        - ${HOME}/.microsoft/usersecretes/:/root/.microsoft/usersecretes
        - ${HOME}/.aspnet/https/:/root/.aspnet/https/
    ports:
        - "8002:80"